export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const FETCH_INITIAL_VALUE_REQUEST = 'FETCH_INITIAL_VALUE_REQUEST';
export const FETCH_INITIAL_VALUE_SUCCESS = 'FETCH_INITIAL_VALUE_SUCCESS';
export const FETCH_INITIAL_VALUE_FAILED = 'FETCH_INITIAL_VALUE_FAILED';
